config/routes.rb
Rails.application.routes.draw do
  resources :imports
  resources :tags
  resources :suppliers
  resources :categories do
    resources :tags
  end
  resources :contries
  get 'utility/upload_token'
  root to: "home#index"
  devise_for :users,  controllers: { registrations: "registrations"}
  resources :products
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { scope: :category_id }
  belongs_to :category
  has_many   :product_tags
  has_many   :products, through: :product_tags

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.where(category_id: params[:category_id])
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @product_tags = ProductTag.where({tag_id: params[:id]}).paginate(page: params[:page], per_page: 30)
    @products = Product.find(@product_tags.map{ |p| p.product_id })
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    # respond_to do |format|
    #   if @tag.save
    #     format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
    #     format.json { render :show, status: :created, location: @tag }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @tag.errors, status: :unprocessable_entity }
    #   end
    # end
    @tag.save
    redirect_to Category.find(tag_params[:category_id])
    return
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    render js: "$('#tag_#{params[:id]}').remove()"
    # respond_to do |format|
    #   format.html { redirect_to edit_category_url(params[:category_id]), notice: 'Tag was successfully destroyed.' }
    #   format.json { head :no_content }
    #   format.js { }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :category_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<span id="tag_<%= tag.id %>" >
    <%=link_to tag.name, tag, class: "badge badge-info"%>
    <%#=link_to 'X', category_tag_path(params[:id], tag.id), method: :delete, remote: true, class: "close" %>
</span>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.category_id %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
    <strong>
        <%= @tag.category.name %>
    </strong>
</h2>

<h3>
    <%= @tag.name %>
    <%= render @tag.category.tags %>
</h3>

<%= will_paginate @product_tags %>
<div class="card-columns text-center">
    <%= render @products  %>
</div>
<%= will_paginate @product_tags %>