config/routes.rb
Rails.application.routes.draw do
  resources :imports
  resources :tags
  resources :suppliers
  resources :categories do
    resources :tags
  end
  resources :contries
  get 'utility/upload_token'
  root to: "home#index"
  devise_for :users,  controllers: { registrations: "registrations"}
  resources :products
end

app/models/product.rb
class Product < ApplicationRecord
  default_scope { where(hidden: false) }
  # default_scope { where(published: true) }
  default_scope { order(:id) }
  has_rich_text :content
  belongs_to :category
  belongs_to :contry
  belongs_to :supplier
  has_many   :product_tags
  has_many   :tags, through: :product_tags

  before_save do |product|
    if not product.content.blank?
      if /src="(.*)"/.match(product.content.to_s)
        product.photo = $1
        pp product.photo
      end
    end
  end

  def destroy
    self.update({hidden: true})
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_title

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page], per_page: 30)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        add_tags(@product.id)
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        add_tags(@product.id)
        format.html { redirect_to @product, notice: I18n.t('successfully.updated') }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: I18n.t('successfully.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :content, :category_id,
                                      :contry_id, :wholesale_price, :market_price,
                                      :supplier_id
                                     )
    end

    def add_tags(product_id)
      unless params[:product_tags].blank?
        ProductTag.where(product_id: product_id).delete_all
        ProductTag.create( params[:product_tags].map { |tag|
                             {product_id: product_id, tag_id: tag}
                           })
      end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
    <% if product.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
                <% product.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <%= form.label :name, class: "input-group-text"  %>
        </div>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <%= form.label :market_price, class: "input-group-text" %>
        </div>
        <%= form.number_field :market_price, class: "form-control" %>
    </div>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <%= form.label :wholesale_price, class: "input-group-text" %>
        </div>
        <%= form.number_field :wholesale_price, class: "form-control" %>
    </div>
    <div data-controller="tags" data-tags-url="/tags.json?category_id=">
        <div class="input-group mb-3">
            <%= form.select :category_id,
                Category.all.collect{|cata| [cata.name, cata.id]},
                {:include_blank => t('Select.category')},
                {'data-action' => "change->tags#category",
                 class: "form-control"
                }
            %>
            <%=link_to "添加分类", new_category_path, class: "btn btn-primary" %>
        </div>

        <span data-target="tags.output">
            <%= render 'tags_checkbox', tags: product.tags  %>
        </span>
        <%=link_to "添加标签",
        categories_path,
        class: "",
            'data-target' => "tags.edit"

        %>

    </div>


    <div class="input-group mb-3">
        <%= form.select :contry_id,
            Contry.all.collect {|cata| [cata.name, cata.id]},
            {include_blank: t('Select.contry')}, {class: "form-control"}
        %>
        <%=link_to "添加国家", new_contry_path, class: "btn btn-primary" %>
    </div>
    <div class="input-group mb-3">
        <%= form.select :supplier_id,
            Supplier.all.collect {|cata| [cata.company, cata.id]},
            { include_blank: t('Select.supplier')}, {class: "form-control"}
        %>
        <%=link_to "添加供应商", new_supplier_path, class: "btn btn-primary" %>
    </div>
    <div>
        <%= form.rich_text_area :content %>
    </div>

    <div class="actions input-group mb-3">
        <%= form.submit %>
    </div>
<% end %>

app/views/products/_product.html.erb
<div class="card shadow-sm" style="width:300px">
    <%= image_tag product.photo || 'http://tmp.dzunion.cn/logo.png', class: 'card-img-top', style: 'height:300px; width:300px;' %>
    <div class="card-header">
        <h5 class="my-0 font-weight-normal">
            <%= link_to product.name, product %>
        </h5>
    </div>
    <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4">
            <li> 市场零售价: <%= product.market_price %> </li>
            <li>规格: <%= product.weight %></li>
            <li> 箱规: <%= product.specification %> </li>
        </ul>
    </div>
    <% if current_user.present? %>
        <div class="card-footer">
            <span><%= link_to t('Edit'), edit_product_path(product), target: '_blank' %></span>
            <span>
                <%= link_to t('Destroy'), product,
                method: :delete,
                remote: true,
                data: { confirm: 'Are you sure?' }
                %>
            </span>
        </div>
    <% end %>
</div>

app/views/products/_tags_checkbox.html.erb
<% tags.each do |tag| %>
    <label>
        <input data-target="tags.checked" name="product_tags[]" type="checkbox" checked value=<%= tag.id %> />
    <%= tag.name %>
</label>
<% end %>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to t('add'), new_product_path, class: 'btn btn-primary' %>
<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.market_price %></td>
        <td><%= product.wholesale_price %></td>
        <td><%= product.category.name %></td>
        <td><%= product.contry.name %></td>
        <td><%= link_to t('Show'), product %></td>
        <td><%= link_to t('Edit'), edit_product_path(product) %></td>
        <td>
            <%= link_to t('Destroy'), product,
            method: :delete,
            remote: true,
            data: { confirm: 'Are you sure?' }
            %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @products %>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
    <%= @product.name %>
</h2>

<div>
    <%= @product.content %>
</div>

<div>
    <%= render @product.tags %>
</div>
<% if current_user.present? %>

    <%= link_to t('Edit'), edit_product_path(@product), class: 'btn-primary btn' %>
<% end %>