config/routes.rb
Rails.application.routes.draw do
  resources :imports
  resources :tags
  resources :suppliers
  resources :categories do
    resources :tags
  end
  resources :contries
  get 'utility/upload_token'
  root to: "home#index"
  devise_for :users,  controllers: { registrations: "registrations"}
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :tags
  has_many :products
end

app/models/contry.rb
class Contry < ApplicationRecord
  validates :name, presence: true
end

app/models/import.rb
class Import < ApplicationRecord
  has_one_attached :csv_file

  def self.parse_csv(file)
    require 'csv'
    first_row = nil
    log_num = 0
    CSV.foreach(file) do |row|
      if first_row == nil
        first_row = row
        next
      end
      row[2].gsub!("\n", ' ')
      row[2].gsub!("\s+", ' ')

      result = Product.create({
                    name: row[2],
                    contry_id: row[1],
                    category_id: row[0],
                    weight: row[4],
                    specification: row[5],
                    wholesale_price: row[6],
                    market_price: row[7],
                    shelf_life: row[8],
                    supplier_id: row[9]
                  })
      if result.errors.any?
        pp result.errors
        exit
      end

      log_num += 1

      tags = row[3].split
      tags.each do |t|
        tag = Tag.find_or_create_by!({name: t, category_id: row[0]})
        ProductTag.create({product_id: result.id, tag_id: tag.id})
      end

    end
    return log_num

  end
end

app/models/product.rb
class Product < ApplicationRecord
  default_scope { where(hidden: false) }
  # default_scope { where(published: true) }
  default_scope { order(:id) }
  has_rich_text :content
  belongs_to :category
  belongs_to :contry
  belongs_to :supplier
  has_many   :product_tags
  has_many   :tags, through: :product_tags

  before_save do |product|
    if not product.content.blank?
      if /src="(.*)"/.match(product.content.to_s)
        product.photo = $1
        pp product.photo
      end
    end
  end

  def destroy
    self.update({hidden: true})
  end
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  validates  :product_id, uniqueness: { scope: :tag_id }
  belongs_to :product
  belongs_to :tag
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :company, presence: true
  validates :company, uniqueness: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: { scope: :category_id }
  belongs_to :category
  has_many   :product_tags
  has_many   :products, through: :product_tags

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  # OPTIMIZE me
  def index
    @products = Product.paginate(page: params[:page], per_page: 30)
  end

  # TODO something
  def show
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :index]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.where(category_id: params[:category_id])
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @product_tags = ProductTag.where({tag_id: params[:id]}).paginate(page: params[:page], per_page: 30)
    @products = Product.find(@product_tags.map{ |p| p.product_id })
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    # respond_to do |format|
    #   if @tag.save
    #     format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
    #     format.json { render :show, status: :created, location: @tag }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @tag.errors, status: :unprocessable_entity }
    #   end
    # end
    @tag.save
    redirect_to Category.find(tag_params[:category_id])
    return
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    render js: "$('#tag_#{params[:id]}').remove()"
    # respond_to do |format|
    #   format.html { redirect_to edit_category_url(params[:category_id]), notice: 'Tag was successfully destroyed.' }
    #   format.json { head :no_content }
    #   format.js { }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contries_helper.rb
module ContriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/utility_helper.rb
module UtilityHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= t('site_title') %></title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

        <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
            <h5 class="my-0 mr-md-auto font-weight-normal">上海优涛商贸</h5>
            <nav class="my-2 my-md-0 mr-md-3">
                <%=link_to "首页", root_path, class: "p-2 text-dark" %>
                <%=link_to "分类", categories_path, class: "p-2 text-dark" %>
                <%=link_to "地区", contries_path, class: "p-2 text-dark" %>
                <% if current_user.present? %>
                    <%=link_to "导入产品", new_import_path, class: "p-2 text-dark" %>
                    <%=link_to "添加产品", new_product_path, class: "p-2 text-dark" %>
                <% end %>
            </nav>
            <% if current_user.present? %>
                <%=link_to "登出", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
            <% else %>
                <%=link_to "登入", user_session_path, class: "btn btn-outline-primary" %>
            <% end %>

        </div>
        <div class="container">
            <h1><%= @title %></h1>
                <%= yield %>

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Features</h5>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Resources</h5>
                    </div>
                    <div class="col-6 col-md">
                        <h5>About</h5>
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>